### ISSUE TITLE
Consecutive lines with formatting that are soft-broken are rendered as two lines

### ISSUE THREAD

**Issue by pingzing** [OffprintStudios/dragonfish-old#117]
The view in the editor:
![image](https://user-images.githubusercontent.com/5133649/90928887-64c53480-e400-11ea-8f5f-f1eb74fa3caa.png)

The view in the reader:
![image](https://user-images.githubusercontent.com/5133649/90928918-71e22380-e400-11ea-8ee5-3aaebe11e4e2.png)

The generated HTML:
```html
<p class="ql-align-center"><em>...are my sunshine... only sunshine...</em>

<em>...when skies are gray...</em>

<em>...never know dear...</em>

<em>...much I love you...</em>

<em>...don't take my sunshine away.</em></p>
```
Pretty sure the issue is the newlines between the `<em>` tags.

**Comment by pingzing** [comment]
A-ha! This is actually an edge case! The issue is that each `<em>` is its own line. If, instead, we italicize the entire block of text, we wind up with
```HTML
<em>
..are my sunshine... only sunshine...
...when skies are gray...
...never know dear...
...much I love you...
...don't take my sunshine away.
</em>
```
...which renders as expected.

**Comment by Figments** [comment]
huh, so basically the italics were set on each line individually?

**Comment by pingzing** [comment]
Yep. if you copy them from, say, Fimfic, that's how they look in the clipboard. We might be able to untangle this in the `TextSoftBreakBlot`'s `textNodeMatcher()`, but it's user-fixable by just highlighting the whole block, turning off italics, then turning them back on.

Not sure if its worth the trouble to fix.

**Comment by Figments** [comment]
got it. let's just do that then and let people know.
